name: Prism
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.5+3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7
  # path_provider: ^1.6.7
  share: ^0.6.4
  url_launcher: ^5.4.5
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  # firebase_messaging: ^6.0.16
  flare_splash_screen: ^3.0.1
  provider: ^4.1.3
  flutter_svg: 0.17.4
  optimized_cached_image: ^0.1.13
  palette_generator: ^0.2.2
  flutter_colorpicker: ^0.3.4
  
# dependency_overrides:
#   image: 2.1.12
  fluttertoast: ^4.0.1
  gallery_saver: ^2.0.1
  firebase_dynamic_links: ^0.5.1
  permission_handler: ^5.0.1+1
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_automation: ^1.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/setups/
    - assets/animations/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 500
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 300
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 400
        - asset: assets/fonts/Proxima Nova Bold.otf
          weight: 600
        - asset: assets/fonts/Proxima Nova Extrabold.otf
          weight: 700
        - asset: assets/fonts/Proxima Nova Black.otf
          weight: 800
        - asset: assets/fonts/Proxima Nova Black.otf
          weight: 900

    - family:  JamIcons
      fonts:
        - asset: assets/fonts/JamIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
